2023/08/20 13:58:37 [error] 30#30: *101619 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:37 [error] 30#30: *101619 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:37 [error] 30#30: *101623 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101632 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101632 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101635 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101637 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101637 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /html/nhome.html HTTP/1.1", upstream: "http://10.1.0.2:1082/html/nhome.html", host: "hub.hasti.co"
2023/08/20 13:58:44 [error] 30#30: *101637 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /api/hpe-restapi.json HTTP/1.1", upstream: "http://10.1.0.2:1082/api/hpe-restapi.json", host: "hub.hasti.co"
2023/08/20 13:58:58 [error] 30#30: *101647 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /favicon2.iso HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon2.iso", host: "hub.hasti.co"
2023/08/20 13:58:58 [error] 30#30: *101647 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /favicon.iso HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon.iso", host: "hub.hasti.co"
2023/08/20 13:58:59 [error] 30#30: *101652 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:59 [error] 30#30: *101652 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:59 [error] 30#30: *101655 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:58:59 [error] 30#30: *101658 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101679 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101679 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101683 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /login.html HTTP/1.1", upstream: "http://10.1.0.2:1082/login.html", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101704 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /xmldata?item=All HTTP/1.1", upstream: "http://10.1.0.2:1082/xmldata?item=All", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101704 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /upnp/BasicDevice.xml HTTP/1.1", upstream: "http://10.1.0.2:1082/upnp/BasicDevice.xml", host: "hub.hasti.co"
2023/08/20 13:59:00 [error] 31#31: *101704 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:01 [error] 31#31: *101729 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /Wsusadmin/Errors/BrowserSettings.aspx HTTP/1.1", upstream: "http://10.1.0.2:1082/Wsusadmin/Errors/BrowserSettings.aspx", host: "hub.hasti.co"
2023/08/20 13:59:01 [error] 31#31: *101731 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:03 [error] 31#31: *101901 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:03 [error] 31#31: *101901 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:03 [error] 31#31: *101904 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /api/sonicos/is-sslvpn-enabled HTTP/1.1", upstream: "http://10.1.0.2:1082/api/sonicos/is-sslvpn-enabled", host: "hub.hasti.co"
2023/08/20 13:59:05 [error] 29#29: *101986 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /home.asp HTTP/1.1", upstream: "http://10.1.0.2:1082/home.asp", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 29#29: *102017 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 29#29: *102017 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 29#29: *102020 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /SAPHostControl/?wsdl HTTP/1.1", upstream: "http://10.1.0.2:1082/SAPHostControl/?wsdl", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 28#28: *102026 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 28#28: *102026 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 29#29: *102030 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /sapmc/sapmc.html HTTP/1.1", upstream: "http://10.1.0.2:1082/sapmc/sapmc.html", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 28#28: *102051 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 28#28: *102051 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:06 [error] 28#28: *102054 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /cgi-bin/authLogin.cgi HTTP/1.1", upstream: "http://10.1.0.2:1082/cgi-bin/authLogin.cgi", host: "hub.hasti.co"
2023/08/20 13:59:08 [error] 28#28: *102179 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:08 [error] 28#28: *102179 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:08 [error] 28#28: *102182 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /qsoap.qap HTTP/1.1", upstream: "http://10.1.0.2:1082/qsoap.qap", host: "hub.hasti.co"
2023/08/20 13:59:09 [error] 30#30: *102284 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /invoker/EJBInvokerServlet HTTP/1.1", upstream: "http://10.1.0.2:1082/invoker/EJBInvokerServlet", host: "hub.hasti.co"
2023/08/20 13:59:09 [error] 30#30: *102284 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /invoker/JMXInvokerServlet HTTP/1.1", upstream: "http://10.1.0.2:1082/invoker/JMXInvokerServlet", host: "hub.hasti.co"
2023/08/20 13:59:09 [error] 30#30: *102289 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /web-console/ServerInfo.jsp HTTP/1.1", upstream: "http://10.1.0.2:1082/web-console/ServerInfo.jsp", host: "hub.hasti.co"
2023/08/20 13:59:11 [error] 30#30: *102332 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:11 [error] 30#30: *102332 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:11 [error] 30#30: *102335 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /i18n/adminconsole_en_us.json HTTP/1.1", upstream: "http://10.1.0.2:1082/i18n/adminconsole_en_us.json", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102374 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102374 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102377 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /js/hpsum/hpsum-version.js HTTP/1.1", upstream: "http://10.1.0.2:1082/js/hpsum/hpsum-version.js", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102377 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /js/hpsum/hpsum-version.js HTTP/1.1", upstream: "http://10.1.0.2:1082/js/hpsum/hpsum-version.js", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102377 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /js/hpsum/hpsum-version.js HTTP/1.1", upstream: "http://10.1.0.2:1082/js/hpsum/hpsum-version.js", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102377 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /js/hpsum/hpsum-version.js HTTP/1.1", upstream: "http://10.1.0.2:1082/js/hpsum/hpsum-version.js", host: "hub.hasti.co"
2023/08/20 13:59:12 [error] 31#31: *102377 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /js/hpsum/hpsum-version.js HTTP/1.1", upstream: "http://10.1.0.2:1082/js/hpsum/hpsum-version.js", host: "hub.hasti.co"
2023/08/20 13:59:13 [error] 31#31: *102396 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:13 [error] 31#31: *102396 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:13 [error] 31#31: *102401 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /HNAP1/ HTTP/1.1", upstream: "http://10.1.0.2:1082/HNAP1/", host: "hub.hasti.co"
2023/08/20 13:59:14 [error] 31#31: *102408 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:14 [error] 31#31: *102408 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:14 [error] 31#31: *102411 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:16 [error] 31#31: *102515 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /test.js HTTP/1.1", upstream: "http://10.1.0.2:1082/test.js", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 29#29: *102576 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 29#29: *102576 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 31#31: *102577 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 31#31: *102577 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 31#31: *102581 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /login.html HTTP/1.1", upstream: "http://10.1.0.2:1082/login.html", host: "hub.hasti.co"
2023/08/20 13:59:18 [error] 29#29: *102584 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /login?redirects=10 HTTP/1.1", upstream: "http://10.1.0.2:1082/login?redirects=10", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 31#31: *102623 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /securecgi-bin/CSUserCGI.exe?ver HTTP/1.1", upstream: "http://10.1.0.2:1082/securecgi-bin/CSUserCGI.exe?ver", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 31#31: *102625 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /deploymentmanager/index.jsp HTTP/1.1", upstream: "http://10.1.0.2:1082/deploymentmanager/index.jsp", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 31#31: *102623 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /securecgi-bin/CSUserCGI.exe?Init+0 HTTP/1.1", upstream: "http://10.1.0.2:1082/securecgi-bin/CSUserCGI.exe?Init+0", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 31#31: *102647 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /self_upgrade.html HTTP/1.1", upstream: "http://10.1.0.2:1082/self_upgrade.html", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 29#29: *102661 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /cgi-bin/kvm.cgi?&file=login HTTP/1.1", upstream: "http://10.1.0.2:1082/cgi-bin/kvm.cgi?&file=login", host: "hub.hasti.co"
2023/08/20 13:59:19 [error] 28#28: *102662 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /snmx-cgi/fxm.exe HTTP/1.1", upstream: "http://10.1.0.2:1082/snmx-cgi/fxm.exe", host: "hub.hasti.co"
2023/08/20 13:59:37 [error] 28#28: *102748 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /qwe/qwe/index.html HTTP/1.1", upstream: "http://10.1.0.2:1082/qwe/qwe/index.html", host: "hub.hasti.co"
2023/08/20 14:00:11 [error] 30#30: *102803 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 14:00:11 [error] 30#30: *102803 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/20 14:00:11 [error] 31#31: *102806 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 14:00:13 [error] 31#31: *102806 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 14:00:17 [error] 31#31: *102806 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 14:00:27 [error] 31#31: *102806 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 14:00:43 [error] 31#31: *102806 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "POST /sdk HTTP/1.1", upstream: "http://10.1.0.2:1082/sdk", host: "hub.hasti.co"
2023/08/20 14:02:02 [error] 28#28: *103103 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /nitro/v1/config/mps HTTP/1.1", upstream: "http://10.1.0.2:1082/nitro/v1/config/mps", host: "hub.hasti.co"
2023/08/20 14:02:09 [error] 28#28: *103125 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /note.txt?F_notini=&T_note=&nomentreprise=blah&filenote=../../windows/win.ini HTTP/1.1", upstream: "http://10.1.0.2:1082/note.txt?F_notini=&T_note=&nomentreprise=blah&filenote=../../windows/win.ini", host: "hub.hasti.co"
2023/08/20 14:02:09 [error] 28#28: *103125 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /note.txt?F_notini=&T_note=&nomentreprise=blah&filenote=../../winnt/win.ini HTTP/1.1", upstream: "http://10.1.0.2:1082/note.txt?F_notini=&T_note=&nomentreprise=blah&filenote=../../winnt/win.ini", host: "hub.hasti.co"
2023/08/20 14:02:09 [error] 30#30: *103129 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /SiteScope/cgi/go.exe/SiteScope?page=eventLog&machine=&logName=System&account=administrator HTTP/1.1", upstream: "http://10.1.0.2:1082/SiteScope/cgi/go.exe/SiteScope?page=eventLog&machine=&logName=System&account=administrator", host: "hub.hasti.co"
2023/08/20 14:02:09 [error] 30#30: *103132 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.240.34, server: hub.hasti.co, request: "GET /..\pixfir~1\how_to_login.html HTTP/1.1", upstream: "http://10.1.0.2:1082/..\pixfir~1\how_to_login.html", host: "hub.hasti.co"
2023/08/27 09:45:23 [error] 29#29: *139823 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/rasa/blobs/sha256:71663fcca60325c4386ab0b58a5fc0f135c5acfff6cf7810faba52dc1cb7ef59 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/rasa/blobs/sha256:71663fcca60325c4386ab0b58a5fc0f135c5acfff6cf7810faba52dc1cb7ef59", host: "docker.hasti.co"
2023/08/27 11:57:06 [error] 31#31: *143330 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/rasa/blobs/sha256:559f23043cd9862cfdfccb76c1f66fa2566fc05e1e784c87ef7e7f24f297c9fa HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/rasa/blobs/sha256:559f23043cd9862cfdfccb76c1f66fa2566fc05e1e784c87ef7e7f24f297c9fa", host: "docker.hasti.co"
2023/08/27 12:57:31 [error] 29#29: *144764 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/rasa/blobs/sha256:eb2c7a0dc65af4a31bb679d2d87d5f9b8ac41cb7d0ffd8511d235599af0a16f6 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/rasa/blobs/sha256:eb2c7a0dc65af4a31bb679d2d87d5f9b8ac41cb7d0ffd8511d235599af0a16f6", host: "docker.hasti.co"
2023/08/30 07:33:52 [error] 30#30: *175238 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:72df5be4a397e07460c255a35d3ac18b1e738f01a6cf8f705508c317045f4f85 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:72df5be4a397e07460c255a35d3ac18b1e738f01a6cf8f705508c317045f4f85", host: "docker.hasti.co"
2023/08/30 08:54:25 [error] 28#28: *175659 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:ef62253632b82451301f33fb1673e9a4eab3a2cc76db81a2e9492ed649b671d8 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:ef62253632b82451301f33fb1673e9a4eab3a2cc76db81a2e9492ed649b671d8", host: "docker.hasti.co"
2023/08/30 11:17:59 [error] 28#28: *180169 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:7558e35e2a91cc57e0fc17baca5d616d6dc1c46291e3e46150d6345743cbdad1 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:7558e35e2a91cc57e0fc17baca5d616d6dc1c46291e3e46150d6345743cbdad1", host: "docker.hasti.co"
2023/08/30 12:36:54 [error] 28#28: *182758 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:244f2f0504222dc26ccef3cda6e306f1f6bd3a393b6e331aab21d79d02c90f36 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:244f2f0504222dc26ccef3cda6e306f1f6bd3a393b6e331aab21d79d02c90f36", host: "docker.hasti.co"
2023/08/30 15:54:43 [error] 29#29: *185151 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/30 15:54:43 [error] 29#29: *185151 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon.ico", host: "hub.hasti.co", referrer: "https://hub.hasti.co/"
2023/08/30 15:54:46 [error] 29#29: *185151 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/08/30 15:54:46 [error] 29#29: *185151 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon.ico", host: "hub.hasti.co", referrer: "https://hub.hasti.co/"
2023/09/02 10:28:34 [error] 28#28: *191580 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:c74b9e6e3231c30412b5e3f2fbd73c2cfafa144d9824be87f0b8cafb9e517505 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:c74b9e6e3231c30412b5e3f2fbd73c2cfafa144d9824be87f0b8cafb9e517505", host: "docker.hasti.co"
2023/09/02 14:02:15 [error] 29#29: *195359 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/09/02 14:02:15 [error] 29#29: *195359 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon.ico", host: "hub.hasti.co", referrer: "https://hub.hasti.co/"
2023/09/02 14:02:20 [error] 29#29: *195359 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET / HTTP/1.1", upstream: "http://10.1.0.2:1082/", host: "hub.hasti.co"
2023/09/02 14:02:20 [error] 29#29: *195359 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.226.116, server: hub.hasti.co, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.1.0.2:1082/favicon.ico", host: "hub.hasti.co", referrer: "https://hub.hasti.co/"
2023/09/04 07:07:08 [error] 28#28: *207035 upstream prematurely closed connection while reading upstream, client: 172.27.226.116, server: docker.hasti.co, request: "GET /v2/alpha/hasti-sentiment/blobs/sha256:9239f9e08f995e6592c365b6a135a915882d09c2341913aa5d740d5eaa266216 HTTP/1.1", upstream: "http://10.1.0.2:1081/v2/alpha/hasti-sentiment/blobs/sha256:9239f9e08f995e6592c365b6a135a915882d09c2341913aa5d740d5eaa266216", host: "docker.hasti.co"
